/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dvs;

import org.apache.log4j.Logger;
import org.apache.spark.SparkConf;
import org.apache.spark.api.java.JavaRDD;
import org.apache.spark.api.java.JavaSparkContext;
import org.bytedeco.opencv.opencv_stitching.Stitcher;
import org.bytedeco.opencv.opencv_videoio.VideoCapture;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {
    //arg 0 is the outputfile
    //arg 1 is time slices
    //one argument for each csv file
    public static void main(String[] args) {
        Logger logger = Logger.getLogger(DVStitcher.class.getName());
        VideoCapture videoCapture1 = new VideoCapture("/tmp/pre/seoul_21_l000.mp4");
        VideoCapture videoCapture2 = new VideoCapture("~/seoul_21_l.mp4");
        logger.info("God please");
        logger.info(videoCapture1.isOpened());
        logger.info(videoCapture2.isOpened());
    }
}
