/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.dvs;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {
    //arg 0 is the outputfile
    //arg 1 is time slices
    //one argument for each csv file
    public static void main(String[] args) {
        int segmentSize = Integer.parseInt(args[1]);
        String[] csvFiles = Arrays.copyOfRange(args, 2, args.length);
        try {
            ArrayList<ArrayList<Segment>> segmentLists = SegmentPreprocessor.makeSegments(csvFiles);
            TaskMaker taskMaker = new TaskMaker(args[0], segmentSize, segmentLists);
            List<Task> tasks = taskMaker.getTasks();
            for(Task task: tasks){
                if(task.getStart() > 5) {
                    System.out.println(task);
                    DVStitcher dvStitcher = new DVStitcher(task);
                    dvStitcher.stitch();
                    break;
                }
            }

//            SparkConf conf = new SparkConf().setAppName("dsvStitching");
//            JavaSparkContext sc = new JavaSparkContext(conf);
//            JavaRDD<Task> taskJavaRDD= sc.parallelize(tasks);
//            JavaRDD<String> outputJavaRDD = taskJavaRDD.map(new StitchFunction(args[0]));
//            outputJavaRDD.collect().forEach(System.out::println);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
